
.apt-template: &apt-template
- export LC_ALL=C.UTF-8
- export DEBIAN_FRONTEND=noninteractive
- echo Etc/UTC > /etc/timezone
- echo 'quiet "1";'
       'APT::Install-Recommends "0";'
       'APT::Install-Suggests "0";'
       'APT::Acquire::Retries "20";'
       'APT::Get::Assume-Yes "true";'
       'Dpkg::Use-Pty "0";'
      > /etc/apt/apt.conf.d/99gitlab
- apt-get update
- apt-get dist-upgrade
- apt-get install git

debian_buster:
  image: debian:buster
  script:
    - echo "deb http://deb.debian.org/debian/ buster-backports main" >> /etc/apt/sources.list
    - *apt-template
    - apt-get install tor/buster-backports
    - apt-get install default-jdk gradle junit4
    - gradle build jar sourcesJar javadocJar writeNewPom

openjdk-14:
  image: openjdk:14-buster
  script:
    - echo "deb http://deb.debian.org/debian/ buster-backports main" >> /etc/apt/sources.list
    - *apt-template
    - apt-get install tor/buster-backports
    - apt-get install gradle
    - gradle build jar sourcesJar javadocJar writeNewPom

openjdk-8:
  image: openjdk:8-stretch
  artifacts:
    paths:
      - build/libs
  script:
    - echo "deb http://deb.debian.org/debian/ stretch-backports-sloppy main" >> /etc/apt/sources.list
    - *apt-template
    - apt-get install tor/stretch-backports-sloppy
    - ./gradlew build jar sourcesJar javadocJar writeNewPom
    - for f in build/libs/*.jar; do sha256sum $f; done

openjdk-8_maven:
  image: openjdk:8-stretch
  artifacts:
    paths:
      - target/jtorctl-*.*
  script:
    - echo "deb http://deb.debian.org/debian/ stretch-backports-sloppy main" >> /etc/apt/sources.list
    - *apt-template
    - apt-get install maven tor/stretch-backports-sloppy
    - mvn verify
    - for f in target/*.jar; do sha256sum $f; done

pages:
  stage: deploy
  image: openjdk:8-stretch
  artifacts:
    paths:
      - public
  script:
    - ./gradlew javadoc
    - test -d public || mkdir public
    - mv build/docs/javadoc/* public/
